[platformio]
default_envs = bluepill_f103c8

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube
platform_packages =
  platformio/toolchain-gccarmnoneeabi@~1.120301.0
monitor_speed = 115200
build_flags =
  -Wall
  -Wextra
  -Werror=return-type
  -Wl,-u,_printf_float
  -D METER_SLAVE_ID=1
  -D METER_POLL_INTERVAL_MS=1000
